let num1=prompt('Enter first number');
let num2=prompt('Enter second number');
let num3=prompt('Enter third number');
let sum = num1+num2+num3;
let product = num1*num2*num3;
let average = (num1+num2+num3)/3;
document.querySelector('#sum').innerHTML='The sum is: ' + sum;
document.querySelector('#product').innerHTML='The product is: ' +product;
document.querySelector('#average').innerHTML='The average is: ' +average;